export const GET_USER = 'GET_USER';
export const GET_COLLECTION_LIST = 'GET_COLLECTION_LIST';
export const GET_COLLECTION_DETAIL = 'GET_COLLECTION_DETAIL';
export const CREATE_COLLECTION = 'CREATE_COLLECTION';
export const DELETE_COLLECTION = 'DELETE_COLLECTION';
export const GET_RECIPE = 'GET_RECIPE';
export const DELETE_RECIPE = 'DELETE_RECIPE';
